### ISSUE TITLE
:style .grass bug?

### ISSUE THREAD

**Issue by RDStone** [neo4j/neo4j-browser#1136] opened 2020-07-09 09:09 UTC
I have edited the .grass sheet in the past with no problems - but 4.1 seems to have me beaten

I used to edit it (and I seem to remember I could give it any name I liked so long as it was saved as a .grass file) drop it in the favourites area and... job done. Not Any More - or so it seems.

If I do this now I am offered two options - save to favourites or put straight into the editor. So, if I put it into the editor and set it going - it chunters for a bit, seems ok and - has no effect on the style whether I call it style.grass or "anythingelse".grass. Stopping and restarting the db has no effect.

If I by-pass the drag and drop and simply paste the new file into the browser - prefixed by :style as a command then I get:

Neo.ClientError.Statement.SyntaxError: Invalid input 'l': expected 'n/N' (line 1, column 3 (offset: 2))
"color: #A5ABB6"
   ^
Which is calling an error in a line I have not touched! If I try using :style and entering only the style statement that I want to change then I get an error message as follow - essentially exactly the same:

:style node.ConRod { defaultCaption: "<id>"

caption: "{desc}"

ERROR

Neo.ClientError.Statement.SyntaxError: Invalid input 'p': expected 't/T' or 'l/L' (line 1, column 3 (offset: 2))
"caption: "{desc}""
   ^

}

Obviously, what I want to happen is that the style sheet is updated and the relevant node (in my particular case now diplays "desc.<property> instead of name.<property>

Ideally, this should be accomlished by using a command direct in the UI to edit only the statement that I want to modify rather than downloading the entire .grass file, editing it and reloading it - though this may be necessary to rename the grass file - which should be possible.

I would not have had the temerity to post this (being a novice) but Michael Hunger asked me to!

I am running Desktop 1.2.9
Neo4j 4.1 in Firefox
Halin
Windows 10

Many thanks

**Comment by OskarDamkjaer** [comment] 2020-07-09 13:45
Thanks for reporting this issue! I'll try to reproduce the errors you run into. Perhaps you could send me an example of what you paste after :style that gives rise to the syntax error you mention?

**Comment by RDStone** [comment] 2020-07-09 15:21
Hi Oskar,

This is the example of the short code I input:

:style
node.ConRod {
  defaultCaption: "<id>";
  caption: "{desc}";
}

I also tried using :style followed by the entire .grass file with only the
above statement modified (it had said caption: "{name}"

But both cases threw up similar errors

Rgds,

Roger

**Comment by RDStone** [comment] 2020-07-09 16:08
I should add that Bloom was also running

**Comment by OskarDamkjaer** [comment] 2020-07-10 08:59
Hmm, I think this error is a good place to start. I'll look into it

**Comment by OskarDamkjaer** [comment] 2020-07-10 10:05
I've found part of the problem, we seem to misinterpret the semicolons when the `Enable multi statement query editor` setting is enabled. So the weird error about lines is because part of the grass is interpreted as cypher, thanks again for reporting this so we can get it fixed! 

It might not be the only issue, but if you try disabling `Enable multi statement query editor`, what other issues do you run into?

**Comment by RDStone** [comment] 2020-07-10 10:07
Many thanks!

**Comment by RDStone** [comment] 2020-07-10 10:09
I will try that now!

**Comment by RDStone** [comment] 2020-07-10 10:17
Interesting! I get no error message - but the grass sheet is not edited
either....

**Comment by OskarDamkjaer** [comment] 2020-07-10 11:21
Yes, I suspect there's more than one issue at hand here. I'll look into it but it might take a little while to get to the bottom of it!

**Comment by RDStone** [comment] 2020-07-10 11:23
Oskar,

If you want something really odd - viewing in Graphileon shows the change
of style .... even as the browser remains as it was...

Maybe I need to close and re-open the db for the browser to update?

Roger

**Comment by OskarDamkjaer** [comment] 2020-07-10 11:50
You shouldn't need to re-open the database. It's definitely something wrong on our end

**Comment by OskarDamkjaer** [comment] 2020-07-14 12:29
Could you try multiline disabled and putting the entire command on one line like so: 
`:style node.ConRod {  defaultCaption: "<id>";  caption: "{desc}";}`

That seemed to do it for me. I'm working to make it work without these workarounds

**Comment by OskarDamkjaer** [comment] 2020-07-14 14:34
I've got a fix for both issues under review right now! Thanks for shedding some light on this issue

**Comment by RDStone** [comment] 2020-07-14 16:36
Delighted to help!

Roger

**Comment by OskarDamkjaer** [comment] 2020-07-15 09:48
Did your issue go away when using the workaround of putting it all on one line and not having multiline editing enabled?

**Comment by RDStone** [comment] 2020-07-15 10:06
Hi Oskar, Just at the moment I have a different (non-DB) project that I
have to pull out all the stops on so I won't get back to this unti late
today, maybe tomorrow - but I will let you know! many thanks,

Roger

**Comment by OskarDamkjaer** [comment] 2020-07-15 10:33
No stress! It'll be a while before we release anyway :)

**Comment by OskarDamkjaer** [comment] 2020-07-23 09:11
This should be fixed now and released in our next release in the end of august! Closing this for now, and if the problem or a similar problem arises, feel free to re-open och open a new issue!

**Closed by OskarDamkjaer** 2020-07-23 09:11 UTC

**Comment by RDStone** [comment] 2020-07-23 14:01
Thank you so much! I am desperately impressed with the response!

Roger
