### ISSUE TITLE
Expended View missing ui elements.

### ISSUE THREAD

**Issue by RayLuxembourg** [neo4j/neo4j-browser#1460] opened 2021-07-05 12:43 UTC
**Description:**
When expending the query view to see the graph, 
The ability to change colors, size, and all the other properties, disappear.

**Expectation:**
Able to change properties from an expanded view.

Attaching Screenshots below.

![Screen Shot 2021-07-05 at 15 45 37](https://user-images.githubusercontent.com/15327989/124473555-28948b80-dda8-11eb-9d9d-0a5753b4b0d9.png)

![Screen Shot 2021-07-05 at 15 46 43](https://user-images.githubusercontent.com/15327989/124473634-3cd88880-dda8-11eb-90d3-1e65ef0c37ab.png)

**Comment by OskarDamkjaer** [comment] 2021-07-05 12:45
Could you expand on this and perhaps provide a picture?

**Comment by RayLuxembourg** [comment] 2021-07-05 12:47
@OskarDamkjaer done.

**Comment by OskarDamkjaer** [comment] 2021-07-05 14:02
Thanks, I'm working to solve this today. Our next release in late august I think, so it'll be a while before you see it in production. I'll provide and update here as the problem is resolved. If you're eager to see and use the fix early our [canary](http://browser-canary.graphapp.io/) updates a few hours after a change is merged to master.

**Comment by RayLuxembourg** [comment] 2021-07-07 06:51
@OskarDamkjaer  it will be included in the electron desktop app for mac as well?

**Comment by OskarDamkjaer** [comment] 2021-07-07 08:23
Yes, it'll be in Neo4j Browser version 4.3.2!

**Closed** 2021-08-09 13:42 UTC
Labels: bug
