### ISSUE TITLE
ServiceUnavailable: WebSocket connection failure even on localhost

### ISSUE THREAD

**Issue by Manish-Giri** [neo4j/neo4j-browser#671] opened 2017-10-31 10:06 UTC
I started neo4j from the terminal (`neo4j start`) and visited `localhost:7474` in the browser, as usual. But now suddenly I'm getting this error - 

> ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being

### Your Environment

| software name  | version
| ---------------|----------
|                |  
| OS             |  Ubuntu 16.04
| Web browser    | FireFox  
| node.js        | 
| npm            |
| yarn           |
| Neo4j Browser  | 3.0.11
| Neo4j          | 3.3.0

### Additional Information
Screenshot - 

![screenshot from 2017-10-31 05-57-39](https://user-images.githubusercontent.com/11348778/32218332-eae3697a-be00-11e7-8d8a-a158796d44c6.png)

I searched for this problem and came across this article on the [Neo4J website KB](https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/) that says - 

> In Neo4j 3.0 and its implementation of the Bolt protocol, if a remote browser connects to Neo4j (http://<remote_neo4j_host>:7474) and attempts to authenticate, the following error may be encountered ...

> To have Bolt accept non-local connections, uncomment this line:
dbms.connector.bolt.address=0.0.0.0:7687

But as you can see from the screenshot, I am on `localhost`, and I'm not sure why this is a non-local connection. 

I'm using Neo4J for a project, and I've always accessed it through `localhost:7474`, so I'm not sure what changed suddenly.

I even uninstalled Neo4J completely, and installed it again.  ~~I ran `sudo neo4j start` in the terminal before visiting `localhost:7474`, but when I run `neo4j status`, it says - `neo4j is not running`.~~

---

So, I investigated a bit further and found out that `neo4j` is indeed running properly. However, as soon as I hit the "connect" button, something shuts down neo4j. This is the same time when I get the "reconnecting" message in orange at the top - 

> Connection to server lost....reconnecting

Screenshot - 
![fail](https://user-images.githubusercontent.com/11348778/32222132-721a40e6-be0e-11e7-9933-aff7a0bab0fc.png)

You can see that `neo4j` is running properly when I run `sudo neo4j service status`. But within a few seconds, when I execute the same command again, it's not running anymore. This shutdown happens as soon as I hit "connect".

**Comment by oskarhane** [comment] 2017-10-31 13:29
Hi and thanks for the report @Manish-Giri 
That doesn't look very good, but I suspect it's not a Neo4j Browser issue.
If you start Neo4j with `neo4j console`, do you get a stack trace when the db exists?

**Comment by Casvalx3r** [comment] 2017-11-03 16:31
I am experiencing the same issues as @Manish-Giri. Here are a few screenshots and logs to help narrow the issue down. I am running neo4j on OSX and installed with Homebrew package management.

![screen shot 2017-11-03 at 12 00 30 pm](https://user-images.githubusercontent.com/33352308/32384811-7d4d51de-c092-11e7-95db-e57379b192a0.png)

![screen shot 2017-11-03 at 12 20 14 pm](https://user-images.githubusercontent.com/33352308/32384842-96738714-c092-11e7-87ce-d9ac216ee174.png)

[Log at 2017-11-03 11-58-17 AM.txt](https://github.com/neo4j/neo4j-browser/files/1441754/Log.at.2017-11-03.11-58-17.AM.txt)

**Comment by cjeiler** [comment] 2017-11-22 02:30
Ran into similar issues on MacOS Sierra, had also installed Neo4j using Homebrew. It turned out that my Java version was incompatible with Neo4j -- I downgraded to JDK and JRE 8, then pointed Neo4j to the correct location (jdk1.8.0_152 in this case). Was then able to log in and change the password successfully over the standard http://localhost:7474 address. Hope this saves others some headaches!

**Comment by oskarhane** [comment] 2017-11-22 09:56
Ah, interesting and it makes sense.
Could you @Casvalx3r and @Manish-Giri check if that resolves your problem as well?

**Comment by whatbird** [comment] 2017-11-27 18:46
@cjeiler thanks much for this.

my problem, in case this helps someone:

i installed neo4j via home brew on macOS 10.13. in the browser, i was seeing:

>  ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

i had installed neo4j via homebrew, and just used `brew cask install java` when prompted to manage the dependency, however i should have used `brew cask install java8`. more-or-less:

> brew cask uninstall java
> brew cask install java8

this solved the above problem. thanks

**Comment by demirhanaydin** [comment] 2017-11-28 08:25
@cjeiler @whatbird uninstalling java and leaving only java8 help me, too. Thanks.

**Comment by benkimball** [comment] 2018-01-03 03:26
FWIW, on Mac OS X 10.13.2 (High Sierra) and Homebrew 1.4.2 I needed to use `brew install caskroom/versions/java8` to get Java 8.

**Comment by keithpjolley** [comment] 2018-01-06 17:07
just ran into this too. seems strange that this issue is closed. downgrading java doesn't seem like the right solution.

**Comment by mcpat1993** [comment] 2018-03-12 10:18
I installed Java8 but I'm still getting that error. Any other suggestions?

**Comment by victoriastuart** [comment] 2018-03-17 03:47
I am also getting this error,

"N/A: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3"

on Firefox v.59 (Arch Linux 86_64 OS).

Can connect in Opera v.51.0.

**Comment by rogeroyer** [comment] 2018-04-16 07:48
Maybe the version of your java-jdk is not compatible.

**Comment by oskarhane** [comment] 2018-04-18 06:54
Since there's no real neo4j browser issue here, I'm going to close this.
Feel free to re-open if none of the suggested solutions above helped.

**Closed by oskarhane** 2018-04-18 06:54 UTC

**Comment by KHBAAW** [comment] 2021-10-05 04:54
I have install neo4j on windows  but I cannot establish  database connection. It gives following error message 

Unable to establish remote connection: Neo4jError: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3
![Screenshot (10)](https://user-images.githubusercontent.com/68842470/135962372-f68fac75-5b1d-4aa8-8aee-4ba028d11fb6.png)

**Comment by OskarDamkjaer** [comment] 2021-10-05 07:38
The screenshots you sent are from the Neo4j Desktop product and not browser, you please reopen on that repo! https://github.com/neo4j-devtools/neo4j-desktop
