### ISSUE TITLE
SHOW DATABASES and the default database access

### ISSUE THREAD

**Issue by Mintactus** [neo4j/neo4j-browser#1270] opened 2021-01-03 20:32 UTC
Important details, primarily:

- Neo4j 4.2.1
- Linux Mint 20
- Neo4j Desktop 1.3.11

- **Steps to reproduce**
- **IMPORTANTE NOTE : Might be a behavior not a bug but it strange**

The command SHOW DATABASES does not work when the user doesn't have the privilege to read the default database.
You can reproduce this by many ways. 

- Actual behavior
The SHOW DATABASES result in an error for users without the default database access.

- Expected behavior
It should act as any database does when you don't have access to it, you don't see it that's it.
This concept of default database is confusing when you have many users.

**Comment by mnd999** [comment] 2021-01-25 13:40
Transferring this issue to neo4j-browser as it seems to be browser specific behaviour.

**Comment by OskarDamkjaer** [comment] 2021-08-20 10:29
@Mintactus Hi! Thanks for spending the effort to try to find the root cause! I think I've found a solution to your problem, this link contains a version of browser that should not have the issue: http://db_fallback.surge.sh/ 

It'd be great if you tried it to make sure it fixed the issue!

**Comment by OskarDamkjaer** [comment] 2022-06-09 07:59
As of #1509 we should handle this case by falling back to the system db.

**Closed by OskarDamkjaer** 2022-06-09 07:59 UTC
